fix: Обновить стиль настроек у badge
Bright-Burn/ConstaConstructor pull request #106
Opened 2023-08-08 09:54 UTC by Hairiane

2023-08-09 04:13 UTC, Hairiane commented
![image](https://github.com/Bright-Burn/ConstaConstructor/assets/113695658/58612a6a-3cbe-412e-ac3a-f74b3b48c164)
иконку справа поставить нельзя, убрали из консты такой вариант

2023-08-27 16:26 UTC, Bright-Burn requested changes

2023-08-27 16:26 UTC, Bright-Burn commented on src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/BadgeSettings/BadgeSettings.tsx
> +import { Icons } from '../../../../coreTypes/iconTypes'
импорт

2023-08-28 05:52 UTC, Bright-Burn approved these changes

2023-08-28 05:52 UTC, merged