Обновить дизайн настроек текста
Bright-Burn/ConstaConstructor pull request #107
Opened 2023-08-09 03:50 UTC by Hairiane

2023-08-09 04:00 UTC, Hairiane commented
![image](https://github.com/Bright-Burn/ConstaConstructor/assets/113695658/88e3c3f5-3e40-4112-9b48-4a84bfc1a365)
отсутствует настройка цвета, т.к. нельзя задать цвет тексту

2023-08-09 06:06 UTC, Hairiane commented
![image](https://github.com/Bright-Burn/ConstaConstructor/assets/113695658/6d0b0609-f56b-4a71-927c-bdb08f50d9ae)
Добавил ещё настройку вида

2023-08-26 17:01 UTC, Bright-Burn requested changes

2023-08-26 17:01 UTC, Bright-Burn commented on src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/TextSettings/textConstants.ts
> +import { AlignTextType, textDecorationType } from '../../../../coreTypes/textTypes'
экспорт из coreTypes

2023-08-27 16:22 UTC, Bright-Burn requested changes

2023-08-27 16:22 UTC, Bright-Burn commented on src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/TextSettings/fileTypes.ts
> +  TextPropSize,
почему fileTypes, просто types.ts

2023-08-28 11:38 UTC, Bright-Burn approved these changes

2023-08-28 11:38 UTC, merged