Обновить дизайн настоек чекбокса
Bright-Burn/ConstaConstructor pull request #109
Opened 2023-08-09 06:39 UTC by Hairiane

2023-08-09 06:40 UTC, Hairiane commented
![image](https://github.com/Bright-Burn/ConstaConstructor/assets/113695658/80041a3b-7fda-4a62-bd64-f62426564e88)

2023-08-26 17:14 UTC, Bright-Burn requested changes

2023-08-26 17:14 UTC, Bright-Burn commented on src/components/FormConstructor/coreTypes/checkboxTypes.ts
> +  intermediate?: boolean
что значит intermediate?

2023-08-27 14:34 UTC, Hairiane commented on src/components/FormConstructor/coreTypes/checkboxTypes.ts
> +  intermediate?: boolean
Свойство компоненты(intermediate - делает чекбокс неопределенным)
![image](https://github.com/Bright-Burn/ConstaConstructor/assets/113695658/b93833a7-854c-4ebc-8fa8-5752697d29ed)

2023-08-27 16:27 UTC, merged