Обновить дизайн настроек комбобокса
Bright-Burn/ConstaConstructor pull request #114
Opened 2023-08-10 09:41 UTC by Hairiane

![image](https://github.com/Bright-Burn/ConstaConstructor/assets/113695658/2e5b48b2-2bcc-40bf-99e1-7786e4de4da6)

2023-08-26 18:34 UTC, Bright-Burn requested changes

2023-08-26 18:34 UTC, Bright-Burn commented on src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/ComboBoxSettings/ItemsService.ts
> +      | string,
string? а тут он точно нужен? и для чего?

2023-08-27 15:02 UTC, Hairiane commented on src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/ComboBoxSettings/ItemsService.ts
> +      | string,
Нужен, меняет текст label, placeholder и caption

2023-08-27 16:33 UTC, Bright-Burn commented on src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/ComboBoxSettings/ItemsService.ts
> +      | string,
просто string отменяет любые другие текстовые типы

2023-08-27 16:33 UTC, merged