Обновить дизайн настроек для текстфилда
Bright-Burn/ConstaConstructor pull request #118
Opened 2023-08-11 07:23 UTC by Hairiane

![image](https://github.com/Bright-Burn/ConstaConstructor/assets/113695658/b9fd53bd-f7f6-47e5-b47b-1a8d52d9aabb)
![image](https://github.com/Bright-Burn/ConstaConstructor/assets/113695658/99991369-a55e-4e70-b85c-589a926e2be0)
![image](https://github.com/Bright-Burn/ConstaConstructor/assets/113695658/39754a69-5c60-4368-9ee2-0c6fd499f5f6)
![image](https://github.com/Bright-Burn/ConstaConstructor/assets/113695658/b639b2c3-d5be-4076-a852-13c2dd5923ca)

2023-08-27 08:30 UTC, Bright-Burn requested changes

2023-08-27 08:30 UTC, Bright-Burn commented on src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/TextFieldSettings/ItemsService.ts
> +        if (propsName === 'label' && checked === true) {
судя по всему cheked это и так булевое значение его не нужно проверять на true
ниже то же самое

2023-08-27 08:30 UTC, Bright-Burn commented on src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/TextFieldSettings/TextFieldSettings.tsx
> +              disabled={!!itemsProps.label ? false : true}
после приведения через !! не нужен тернарник на тру фолс
ниже то же самое

2023-08-28 05:56 UTC, Bright-Burn requested changes

2023-08-28 05:56 UTC, Bright-Burn commented on src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/TextFieldSettings/TextFieldSettings.tsx
> +              disabled={!!!itemsProps.label}
у тебя тут и ниже тройное отрицание, оставь только !!

P.S. в остальных прах тоже проверь

2023-08-28 10:25 UTC, Hairiane commented on src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/TextFieldSettings/TextFieldSettings.tsx
> +              disabled={!!!itemsProps.label}
Не, так и нужно, ведь если мы оставим !! то у нас поля будет в дизейбле и мы ничего не сможем написать
[image](https://user-images.githubusercontent.com/113695658/263541987-2c012b66-dfd4-475c-89f4-8fbcc85bcf40.png)

2023-08-28 12:29 UTC, Bright-Burn commented on src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/TextFieldSettings/TextFieldSettings.tsx
> +              disabled={!!!itemsProps.label}
!

2023-08-28 13:33 UTC, merged