Поменять дизайн реестра базовых компонент
Bright-Burn/ConstaConstructor pull request #123
Opened 2023-08-17 06:09 UTC by Hairiane

![image](https://github.com/Bright-Burn/ConstaConstructor/assets/113695658/9c589b85-5ef2-4e25-b085-9071741be9d9)

2023-08-27 10:11 UTC, Bright-Burn requested changes

2023-08-27 10:11 UTC, Bright-Burn commented on src/components/FormConstructor/FormConstructorFormBlockConfigure/Elements/PrototypeRectElement/mocks.ts
> +export const CustomTextMockId2 = uuid();
CustomTextMockId2 почему 2?

2023-08-27 10:11 UTC, Bright-Burn commented on src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/ComponentsStructure/BaseComponents/BaseComponentCardsList/ComponentsDict.ts
> +  [CustomTextMockId2]: 'Tables',
дубль?

2023-08-27 10:11 UTC, Bright-Burn commented on src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/ComponentsStructure/BaseComponents/BaseComponentCardsList/BaseComponentCardsList.tsx
> -      <BaseComponentGroupCard
а в новых макетах нет разделения пока все вместе в одной куче?
мб не удалять а закомменитровать просто с пояснением мол понадобится для группировки базовых компонент?

2023-08-27 16:22 UTC, Hairiane commented on src/components/FormConstructor/FormConstructorFormBlockConfigure/Elements/PrototypeRectElement/mocks.ts
> +export const CustomTextMockId2 = uuid();
CustomTextMockId уже есть, Ирек создавал эти компоненты, не знаю нужны ли они вообще
![image](https://github.com/Bright-Burn/ConstaConstructor/assets/113695658/2e3893ae-e868-4788-813c-386c7d62fc46)

2023-08-27 16:22 UTC, Hairiane commented on src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/ComponentsStructure/BaseComponents/BaseComponentCardsList/ComponentsDict.ts
> +  [CustomTextMockId2]: 'Tables',
![image](https://github.com/Bright-Burn/ConstaConstructor/assets/113695658/88a6de1b-1cea-4242-b4c2-eecf2be59423)
один текстовый другой прямоугольник

2023-08-27 16:26 UTC, Hairiane commented on src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/ComponentsStructure/BaseComponents/BaseComponentCardsList/BaseComponentCardsList.tsx
> -      <BaseComponentGroupCard
В дизайне нет, я пока что скрыл их всех

2023-08-29 05:26 UTC, Bright-Burn requested changes

2023-08-29 05:26 UTC, Bright-Burn commented on src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/ComponentsStructure/BaseComponents/BaseComponentCardsList/BaseComponentGroupCard/BaseComponentGroupCard.tsx
> +        <ResponsesEmptyPockets
вроде как ты уже создавал этот компонент NotFound

2023-08-29 05:26 UTC, Bright-Burn commented on src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/ComponentsStructure/BaseComponents/BaseComponentCardsList/BaseComponentsCard/styles.module.css
> +  width: 96px;
замени все px yf rem

2023-08-29 05:26 UTC, Bright-Burn commented on src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/ComponentsStructure/BaseComponents/BaseComponentCardsList/ComponentsDict.ts
> +  [placeholderMock.id]: 'Tables',
а почему тут через . id вытаскивается а в других переменная указывает на значение?

2023-08-29 05:26 UTC, Bright-Burn commented on src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/ComponentsStructure/BaseComponents/BaseComponentCardsList/ComponentsDict.ts
> +  [CustomTextMockId2]: 'Tables',
тут надо переименовать, так оставлять нельзя, надо давать имена переменным так, чтобы они четко отражали то чем они являются

2023-08-29 12:06 UTC, Bright-Burn approved these changes

2023-08-29 12:06 UTC, merged