Props refactoring
Bright-Burn/ConstaConstructor pull request #124
Opened 2023-08-20 08:50 UTC by EugeneKilld

1) В coretypes/types добавлено:
`export type BrandProps<T, ElementTypes extends AllElementTypes> = {
  type: ElementTypes
  props: T
}`
2) Все пропсы расширены до BrandProps
3) Выбор окна настройки в отдельном компоненте
4) Добавлен тип для Breadcrumbs и ChoiceGroup: 
`export type DeepWriteable<T> = { -readonly [P in keyof T]: DeepWriteable<T[P]> }`
Наверно от него надо как-то избавиться
5) Все остальное переписано под новые пропсы

2023-08-22 05:15 UTC, Hairiane requested changes

2023-08-22 05:15 UTC, Hairiane commented on src/components/FormConstructor/coreTypes/types.ts
> +}
тут ещё filled?:boolean

2023-08-22 05:15 UTC, Hairiane commented on src/components/FormConstructor/FormConstructorFormBlockConfigure/Elements/ButtonFormElement/ButtonFormElement.tsx
> +  const isFilled = element.props.props.filled
правильнее element.props.filled, в element.props.props.filled у нас ничего не прокидывается

2023-08-22 05:15 UTC, Hairiane commented on src/components/FormConstructor/FormConstructorFormBlockConfigure/Elements/TextFieldFormElement/TextFieldFormElement.tsx
> +  const isFilled = element.props.props.filled
тоже самое

2023-08-22 05:15 UTC, Hairiane commented on src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/BaseSettings/PaddingService.ts
> +      console.log(newProps)
логи

2023-08-22 05:15 UTC, Hairiane commented on src/components/FormConstructor/FormConstructorFormBlockConfigure/Elements/DatePickerFormElement/DatePickerFormElement.tsx
> +  console.log(element)
лог

2023-08-22 05:15 UTC, Hairiane commented on src/components/FormConstructor/FormConstructorFormBlockConfigure/Elements/PrototypeRectElement/PrototypeRectElement.tsx
> +  console.log(element)
лог

2023-08-22 13:22 UTC, n19z commented on src/components/FormConstructor/coreTypes/types.ts
> +}
не совсем понимаю. Ты предлагаешь так?

`export type BrandProps<T, ElementTypes extends AllElementTypes> = {
  type: ElementTypes
  props: T
  filled?: boolean
}`

у нас же в UnionProps тип расширится потом свойством filled, или не о том речь?)

2023-08-22 14:03 UTC, Hairiane commented on src/components/FormConstructor/coreTypes/types.ts
> +}
Да

2023-08-22 14:10 UTC, Bright-Burn commented on src/components/FormConstructor/coreTypes/types.ts
> +}
а надо?

2023-08-22 14:20 UTC, Bright-Burn commented on src/components/FormConstructor/coreTypes/types.ts
> +}
может надо указать для конкретных компонентов тогда просто что у них есть доп пропс filled?

2023-08-22 14:24 UTC, Bright-Burn commented on src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/SettingsPanelQualifier.tsx
> +            <FilledSettings />
насколько я понимаю этот компонент надо удалить вообще?

2023-08-22 14:26 UTC, Hairiane commented on src/components/FormConstructor/coreTypes/types.ts
> +}
Можно так

2023-08-22 14:29 UTC, Bright-Burn commented on src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/SettingsPanelQualifier.tsx
> +            <FilledSettings />
пардон он просто в состав других настроек вошел

2023-08-24 10:34 UTC, EugeneKilld commented on src/components/FormConstructor/coreTypes/types.ts
> +}
так?

2023-08-24 10:35 UTC, EugeneKilld commented on src/components/FormConstructor/FormConstructorFormBlockConfigure/Elements/ButtonFormElement/ButtonFormElement.tsx
> +  const isFilled = element.props.props.filled
добавил такое поле только для button и textField

2023-08-24 10:35 UTC, EugeneKilld commented on src/components/FormConstructor/FormConstructorFormBlockConfigure/Elements/TextFieldFormElement/TextFieldFormElement.tsx
> +  const isFilled = element.props.props.filled
.

2023-08-24 10:35 UTC, EugeneKilld commented on src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/BaseSettings/PaddingService.ts
> +      console.log(newProps)
убрал

2023-08-24 10:35 UTC, EugeneKilld commented on src/components/FormConstructor/FormConstructorFormBlockConfigure/Elements/DatePickerFormElement/DatePickerFormElement.tsx
> +  console.log(element)
удалено

2023-08-24 10:35 UTC, EugeneKilld commented on src/components/FormConstructor/FormConstructorFormBlockConfigure/Elements/PrototypeRectElement/PrototypeRectElement.tsx
> +  console.log(element)
удалено

2023-08-24 11:10 UTC, Hairiane commented on src/components/FormConstructor/coreTypes/types.ts
> +}
> так?

Там Ильгиз до этого поменял, он не стал менять тип BrandTextField и BrandButton, там изначально лежал пропс filled он через них прокинул, наверно стоит лучше откатить последний коммит

2023-08-24 13:04 UTC, EugeneKilld commented on src/components/FormConstructor/coreTypes/types.ts
> +}
ok

2023-08-24 14:42 UTC, Hairiane commented on src/components/FormConstructor/coreTypes/types.ts
> +}
> Вернул как было. Только удалил для Union типа { filled?: boolean }. Он же не нужен там теперь, я правильно понял?

Хорошо, не нужен

2023-08-25 07:35 UTC, Hairiane approved these changes

2023-08-25 09:23 UTC, merged