feat: :art: Добавил компонент консты Breadcrumbs
Bright-Burn/ConstaConstructor pull request #66
Opened 2023-06-20 08:40 UTC by Hairiane

2023-06-22 09:02 UTC, gubaydullinir requested changes

2023-06-22 09:02 UTC, gubaydullinir commented on src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/BreadcrumbsSettings/BreadcrumbsSettings.tsx
Попробуй избавиться от "as"

2023-06-23 04:40 UTC, gubaydullinir requested changes

2023-06-23 04:40 UTC, gubaydullinir commented on src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/BreadcrumbsSettings/ItemsService.ts
> +  }
Пустая строка
Если объявление переменной более одной строки, то до и после добавляем пустую строку

2023-06-23 04:40 UTC, gubaydullinir commented on src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/BreadcrumbsSettings/ItemsService.ts
> +  }
Пустоя строка

2023-06-23 04:40 UTC, gubaydullinir commented on src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/BreadcrumbsSettings/ItemsService.ts
> +        if (Number(value) > currentLength) {
Логические конструкции отделяем пустыми строками

2023-06-27 08:33 UTC, Bright-Burn approved these changes

2023-06-27 08:33 UTC, Bright-Burn commented on src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/BreadcrumbsSettings/ItemsService.ts
> +  const getButtonElementProps = (x: UnionProps): x is BreadcrumbProps => 'label' in x
проверка очень странная и название метода не соответствует действительности, должно начинаться с is

2023-06-27 08:33 UTC, Bright-Burn commented on src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/BreadcrumbsSettings/ItemsService.ts
> +      if (selectedElementProps && getButtonElementProps(selectedElementProps)) {
рекомендуется избегать вложенных условий второго уровня тем более еще на 3 уровень переносить

2023-06-27 08:33 UTC, Bright-Burn commented on src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/BreadcrumbsSettings/ItemsService.ts
> +  const getButtonElementProps = (x: UnionProps): x is BreadcrumbProps => 'label' in x
и вообще код этот не работает..

2023-06-27 10:38 UTC, Bright-Burn approved these changes

2023-06-27 10:42 UTC, Bright-Burn approved these changes

2023-06-27 10:42 UTC, Bright-Burn approved these changes

2023-06-27 10:46 UTC, gubaydullinir approved these changes

2023-06-29 05:14 UTC, merged