Add border in layout settings
Bright-Burn/ConstaConstructor pull request #70
Opened 2023-06-23 10:30 UTC by Hairiane

2023-06-30 04:33 UTC, Andrew161644 approved these changes

2023-06-30 04:33 UTC, Andrew161644 commented on src/components/FormConstructor/utils/useDebounceCallBack.ts
> +export function useDebouncedCallback<A extends any[]>(
Такс, дебаунсер, если вкратце зачем здесь нужен?

2023-06-30 04:44 UTC, Andrew161644 requested changes

2023-06-30 04:44 UTC, Andrew161644 commented on src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/LayoutSettings/LayoutSettings.tsx
> +  const borderStyle: BorderStyle[] = [
А как убрать бордер ? Как будто бы не хватает такой возможности.

2023-06-30 04:45 UTC, Andrew161644 commented on src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/LayoutSettings/LayoutSettings.tsx
> +  const borderStyle: BorderStyle[] = [
![Uploading image.png…]()

2023-06-30 05:34 UTC, Bright-Burn commented on src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/LayoutSettings/LayoutSettings.tsx
> +  const borderStyle: BorderStyle[] = [
![image](https://github.com/Bright-Burn/ConstaConstructor/assets/56593131/fa246bb3-99c0-4c84-82ec-b64c42f0ae1c)
вроде через это можно

2023-06-30 05:37 UTC, Bright-Burn requested changes

2023-06-30 05:37 UTC, Bright-Burn commented on src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/LayoutSettings/LayoutSettings.tsx
> +      // @ts-ignore
слишком много игноров, давай избавимся по максимуму 
+ undefined в полях убери 
![image](https://github.com/Bright-Burn/ConstaConstructor/assets/56593131/ab0f40f6-32c9-48da-8c53-27e6d6f559f7)

2023-06-30 05:40 UTC, Bright-Burn requested changes

2023-06-30 05:40 UTC, Bright-Burn commented on src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/LayoutSettings/LayoutSettings.tsx
> +  const onChangeBorderWidth = (value: string | null) => {
так же не хватает возможности указать бордер только для одной стороны контейнера. Это наиболее используемая функциональность, редко приходится указывать бордер для всего контейнера

2023-07-05 06:39 UTC, Andrew161644 requested changes

2023-07-05 06:39 UTC, Andrew161644 commented on src/components/FormConstructor/utils/useDebounceCallBack.ts
> +export function useDebouncedCallback<A extends any[]>(
Напиши пожалуйста комментарий в коде зачем нужен этот дебаунсер.

2023-07-05 06:39 UTC, Andrew161644 commented on src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/LayoutSettings/LayoutSettings.tsx
> +  }, [itemsProps.selectedElementProps])
![изображение](https://github.com/Bright-Burn/ConstaConstructor/assets/43961313/8d5ae0ec-b8e5-46ff-82cb-2715cc5ef861)

Может стоит добавить none как дефолтное свойство, а то не понятно получается для незнающего человека. И лучше поднять его первым в списке

2023-07-05 06:44 UTC, Andrew161644 commented on src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/LayoutSettings/LayoutSettings.tsx
> +  }, [itemsProps.selectedElementProps])
И само поле BorderStyle сразу после HorizontalAlign

2023-07-05 06:58 UTC, Andrew161644 requested changes

2023-07-05 06:58 UTC, Andrew161644 commented on src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/LayoutSettings/ItemsService.ts
> +      onDispatch(selectedElement, newProps)
Есть баг Включена сетка => устанавливаем бордер => настраиваем => отключаем бордер = сетки больше не показывается
Так происходит потому что none перекрывает установку сетки. none Можно вообще убрать и первым пунктом в меню сделать пустую строку и при ее выборе делать null в пропсе borderStyle. Должно помочь.

2023-07-05 10:11 UTC, Bright-Burn approved these changes

2023-07-05 10:13 UTC, merged