Добавить возможность переходить по элементам через дерево
Bright-Burn/ConstaConstructor pull request #76
Opened 2023-07-03 10:08 UTC by Hairiane

2023-07-03 12:30 UTC, Bright-Burn commented on src/components/FormConstructor/store/formElements/types.ts
> +  page?: string
тут надо бы не имя а id страницы хранить

2023-07-03 12:30 UTC, Bright-Burn commented on src/components/FormConstructor/store/formElements/types.ts
> +  page?: string
тоже самое

2023-07-03 12:30 UTC, Bright-Burn commented on src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/ComponentsStructure/ComponentTree/Tree/Tree.tsx
> +    }
этот код не годится совсем, надо при изменении выбранного элемента в дереве чекать принадлежит он текущей активной странице или нет, если нет то менять страницу

2023-07-03 12:30 UTC, Bright-Burn commented on src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/ComponentsStructure/ComponentItems/ComponentCard/ComponentCardUser/ComponentCardUser.tsx
> +      page: activePage?.name,
мб id страницы надо просто в слайсе добавлять
1. тогда не придется в каждом элементе прописывать его
2. в твоем решении может получиться нарушение инварианта, если кто то забудет добавить page

2023-07-03 15:44 UTC, Bright-Burn requested changes

2023-07-03 15:44 UTC, Bright-Burn commented on src/components/FormConstructor/store/formElements/types.ts
> +  idPage?: string
pageId - правильно

2023-07-03 15:44 UTC, Bright-Burn commented on src/components/FormConstructor/store/formElements/slices.ts
> +      const activePageName = state.pages.find(page => page.isActive === true)?.name
уже лучше, но лучше привязываться не к имени а к id страницы

2023-07-04 14:29 UTC, Bright-Burn requested changes

2023-07-04 14:29 UTC, Bright-Burn commented on src/components/FormConstructor/store/formElements/slices.ts
> +  pages: [{ name: 'Page1', isActive: true, parentId: 'root', id: uuid() }],
у рута надо оставить root

2023-07-04 14:29 UTC, Bright-Burn commented on src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/FormBlock/Pages/Pages.tsx
> +    dispatch(formConstructorSlice.actions.changeActivePage({ id: pages[index].id }))
а почему индекс а не uuid?

2023-07-04 14:29 UTC, Bright-Burn commented on src/components/FormConstructor/store/formElements/slices.ts
> +      if (action.payload.element && activePageId) action.payload.element.pageId = activePageId
тут не должно быть if
делаем переменную element  деструктурируем в нее action.payload.element и добавляем свойство pageId

2023-07-05 06:04 UTC, Andrew161644 requested changes

2023-07-05 06:04 UTC, Andrew161644 commented on src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/ComponentsStructure/ComponentItems/ComponentCard/ComponentCardBreadcrumb/ComponentCardBreadcrumb.tsx
> +      page: activePage?.name,
Сюда класть это не правильно. Переход на страницу можно отследаить по дереву. 
Будем закрывать этот ПР последним. Лучше другой подход продумать по переходу

2023-07-05 06:11 UTC, Andrew161644 commented on src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/ComponentsStructure/ComponentItems/ComponentCard/ComponentCardBreadcrumb/ComponentCardBreadcrumb.tsx
> +      page: activePage?.name,
Инициализировать при перетаскивании активную страницу - плохая идея во первых придется на каждый жлемент писать такую логику и сохранять ссылку. Это можно реализовать глобально в логике работы с деревом. 
Предлагаю пока отложить в общем эту штуку

Как вариант - в проекте есть функция поиска потомка для выбранного элемента, можно на базе этой функции написать еще одну, только искать до страниц. И найденную страницу делать выбранной.

2023-07-05 09:37 UTC, Hairiane commented on src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/ComponentsStructure/ComponentItems/ComponentCard/ComponentCardBreadcrumb/ComponentCardBreadcrumb.tsx
> +      page: activePage?.name,
> Сюда класть это не правильно. Переход на страницу можно отследаить по дереву. Будем закрывать этот ПР последним. Лучше другой подход продумать по переходу

Уже переделал, это старый способ

2023-07-05 09:38 UTC, Hairiane commented on src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/FormBlock/Pages/Pages.tsx
> +    dispatch(formConstructorSlice.actions.changeActivePage({ id: pages[index].id }))
> а почему индекс а не uuid?

По определённому индексу передаём id uuid

2023-07-05 10:52 UTC, Hairiane commented on src/components/FormConstructor/store/formElements/slices.ts
> +      if (action.payload.element && activePageId) action.payload.element.pageId = activePageId
> тут не должно быть if делаем переменную element деструктурируем в нее action.payload.element и добавляем свойство pageId

element имеет тип null из за этого без if никак

2023-07-10 12:07 UTC, closed without merging