feat: Добавить два новых компонента Tag и ChoiceGroup
Bright-Burn/ConstaConstructor pull request #85
Opened 2023-07-07 14:12 UTC by Hairiane

2023-07-10 11:43 UTC, Bright-Burn requested changes

2023-07-10 11:43 UTC, Bright-Burn commented on src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/ComponentsStructure/ComponentItems/ComponentCard/ComponentCardChoiceGroup/ComponentCardChoiceGroup.tsx
> +        label: 'fdsffsdf',
Поменяй на что то более вразумительное )
например "Один" "Два" "Три"

2023-07-10 11:44 UTC, Hairiane commented on src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/ComponentsStructure/ComponentItems/ComponentCard/ComponentCardChoiceGroup/ComponentCardChoiceGroup.tsx
> +        label: 'fdsffsdf',
Ой,хорошо

2023-07-11 07:18 UTC, Bright-Burn approved these changes

2023-07-11 07:38 UTC, merged